server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: admin
    password: 12345678
    url: jdbc:mysql://database-1.cbglttlgq40x.us-east-1.rds.amazonaws.com:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
